name: Collect Random Influencers

on:
  schedule:
    - cron: "0 9 * * *" # 매일 오전 9시 (UTC)
  workflow_dispatch: # 수동 실행 가능

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Random Influencers
        run: |
          echo "무작위 인플루언서 데이터 수집 시작..."
          curl -X POST \
            'https://mwxwwaljfbbtwuerevcx.supabase.co/functions/v1/sync-youtube-data' \
            -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eHd3YWxqZmJidHd1ZXJldmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTMwMzIsImV4cCI6MjA3Mzg2OTAzMn0.-6zg7LyylocpOmYGWOfuiVdo_tH_sQLyCvHg-TW-MMU' \
            -H 'Content-Type: application/json' \
            -d '{}'

      - name: Check response
        run: |
          echo "무작위 인플루언서 데이터 수집이 완료되었습니다."
